[phases.setup]
nixPkgs = ["python312", "curl"]

[phases.install]
cmds = [
  "curl -LsSf https://astral.sh/uv/install.sh | sh",
  "export PATH=$HOME/.cargo/bin:$PATH",
  "uv sync"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "uv run gunicorn app.wsgi:application --bind 0.0.0.0:${PORT:-8000}"